# Marvel API Authentication: https://developer.marvel.com/documentation/authorization
# Duplicate this file removing the "_template" prefix from its name to make it work
ts: insert your "ts" here
public_key: insert your "public_key" here
private_key: insert your "private_key" here
md5_hash: insert your "md5_hash" here